apiVersion: v1
kind: Service
metadata:
  name: auth-service
  labels:
    app: reporty
    role: master
    tier: backend
spec:
  ports:
  - port: 3020
    targetPort: 3020
  - port: 3030
    targetPort: 3030
  selector:
    app: reporty
    role: master
    tier: backend